# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vq7pBREU-TvlAcFTtCrATWsAEmOqLroe
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.datasets import load_iris

st.set_page_config(page_title="App")
# Load model once
@st.cache_resource
def load_model():
    return joblib.load("random_forest_model.pkl")

model = load_model()

# Page Navigation
st.set_page_config(page_title="Iris Classifier", page_icon="🌸", layout="centered")

pages = {
    "📊 Data Description": "description",
    "🔍 Predict Iris": "predict",
    "ℹ️ About App": "about"
}

st.sidebar.title("Navigation")
selected_page = st.sidebar.radio("Go to", list(pages.keys()))

# --- Page 1: Data Description ---
if pages[selected_page] == "description":
    st.title("📊 Data Description")

    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['target'] = iris.target
    df['species'] = df['target'].map(dict(zip(range(3), iris.target_names)))

    st.write("### Sample of the Iris Dataset")
    st.dataframe(df.head())

    st.write("### Feature Descriptions")
    st.markdown("""
    - **Sepal Length & Width**: Outer part of the flower.
    - **Petal Length & Width**: Inner part of the flower.
    - **Target**: Encoded as 0 (setosa), 1 (versicolor), 2 (virginica)
    """)

# --- Page 2: Prediction ---
elif pages[selected_page] == "predict":
    st.title("🔍 Predict Iris Species")

    sepal_length = st.slider("Sepal Length (cm)", 4.0, 8.0, 5.8)
    sepal_width = st.slider("Sepal Width (cm)", 2.0, 4.5, 3.0)
    petal_length = st.slider("Petal Length (cm)", 1.0, 7.0, 4.0)
    petal_width = st.slider("Petal Width (cm)", 0.1, 2.5, 1.2)

    if st.button("Predict"):
        input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
        prediction = model.predict(input_data)[0]
        species = {0: "Setosa", 1: "Versicolor", 2: "Virginica"}
        st.success(f"The predicted Iris species is: **{species[prediction]}**")

# --- Page 3: About ---
elif pages[selected_page] == "about":
    st.title("ℹ️ About This App")
    st.markdown("""
    This is a simple multi-page Streamlit app for classifying **Iris flowers** using a pre-trained **Random Forest model**.

    #### 🛠 Built With:
    - Python
    - Streamlit
    - Scikit-learn
    - Joblib

    #### 👨‍💻 Created by:
    - Your Name or Organization
    """)
